### ISSUE TITLE
Possible typo for "during the interview"

### ISSUE THREAD

**Issue by whoyawn** [jwrubel/flipped-interview#1]
> As an outcome here each **candidate** should provide independent feedback on the candidate based on whatever you've established as a process. Personally I think it's important that interviewers not discuss candidates with each other prior to submitting feedback.

Should it be "each interviewer"?

**Comment by jwrubel** [comment]
Good call! If you want to PR it, feel free, or I’ll take care of it in a bit.

**Comment by whoyawn** [comment]
PR at #2
